// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/folder/[id].tsx";
import * as $1 from "./routes/index.tsx";
import * as $$0 from "./islands/CreateButton.tsx";
import * as $$1 from "./islands/CreateModal.tsx";

const manifest = {
  routes: {
    "./routes/folder/[id].tsx": $0,
    "./routes/index.tsx": $1,
  },
  islands: {
    "./islands/CreateButton.tsx": $$0,
    "./islands/CreateModal.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
